apiVersion: apps/v1
kind: Deployment
metadata:
  name: show-app
  labels:
    app: bms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bms
  template:
    metadata:
      labels:
        app: show-app
    spec:
      containers:
      - name: show-app-container
        image: master101/app-show:latest  # Replace with your Docker image
        ports:
        - containerPort: 3000  # Replace with the port your app runs on
